create table if not exists ft_db_{{ params.env }}.data_warehouse.click (
  idlog_file_control number(10) not null default 0,
  idclick_log number(9) not null default 0,
  event_date date not null default '1990-01-01'::date,
  idplacement number(8) not null default 0,
  idcreative number(8) not null default 0,
  idcampaign number(9) not null default 0,
  idcreative_config number(10) not null default 0,
  guidn number(20) not null default 0,
  idevent_type number(3) not null default 0,
  iab_flag char(1) not null default 'w',
  rule_flags number(3) not null default 0,
  idad_index number(10) not null default 0,
  idft_geo number(10) not null default 0,
  ipn number(11) not null default 0 comment 'ip number',
  idsite number(5) not null default 0,
  ft_custom varchar(250) default null,
  idft_agents_cons number(8) not null default 0,
  idlog_keyword number(10) default null,
  ft_section varchar(250) default null,
  device_id varchar(128) default null comment 'external system id (eg idfa)',
  user_ids varchar(500) default null comment 'custom user ids eg. device 9',
  idft_agents_os number(5) not null default 0,
  idft_agents_browsers number(8) not null default 0,
  idft_agents_devices number(5) not null default 0,
  device_type number(3) not null default 0 comment '1 = mobile ; 2 = tablet ; 3 = desktop ; 0 = other ;',
  country_code char(2) not null default '##',
  metro_code number(8) not null default 0 comment '0 - country code valid only',
  region_code number(8) not null default 0,
  city_code number(8) not null default 0,
  postal_code varchar(12) not null default '',
  idft_isp number(8) not null default 0,
  idft_connection_speed number(3) not null default 0,
  event_time timestamp_ntz not null default '1990-01-01 00:00:01'::timestamp_ntz comment 'gmt offset according to campaign',
  device_id_expire_time datetime default null,
  device_id_match_type char(1) default null,
  impression_id number(20) not null default 0,
  idagent_env number(1) not null default 0 comment 'impression was served: 1 = in app ; 0 = other ;',
  log_keywords varchar(500) default null,
  ft_product varchar(250) default null comment 'product code - updated by state request',
  ft_data varchar(250) default null comment 'custom data - updated by state request',
  idbusiness_entity number(5) not null default 0,
  ft_tpplid varchar(50) default null,
  ft_c1 varchar(250) default null,
  ft_c2 varchar(250) default null,
  ft_c3 varchar(250) default null,
  agent_string varchar(250) default null,
  impression_guid varchar(40) default null,
  file_source varchar(),
  load_timestamp timestamp_ntz,
  run_datehour bigint
);

create table if not exists ft_db_{{ params.env }}.data_warehouse.imp (
  idlog_file_control number(10) not null default 0,
  idimpression_log number(9) not null default 0,
  event_date date not null default '1990-01-01'::date,
  idcampaign number(9) not null default 0,
  idad_index number(10) not null default 0,
  rule_flags number(3) not null default 0 comment 'binary string for which rules used',
  geo_db char(1) not null default '-' comment 'geo data base used',
  ft_custom varchar(250) default null comment 'ft_custom_string',
  ft_section varchar(250) default null comment 'ft section field data',
  privacy_flag char(1) not null default 'x',
  placement_tree_id number(8) not null default 0,
  placement_tree_type char(1) not null default '' comment 'determine the type of tree used eg std, hedge',
  placement_path varchar(300) default null,
  creative_tree_id number(8) not null default 0,
  creative_tree_type char(1) not null default '' comment 'determine the type of tree used eg std, hedge',
  creative_path varchar(300) default null,
  idft_agents_os number(5) not null default 0,
  idft_agents_browsers number(8) not null default 0,
  idft_agents_devices number(8) not null default 0,
  device_type number(3) not null default 0 comment '1 = mobile ; 2 = tablet ; 3 = desktop ; 0 = other ;',
  country_code char(2) not null default '##',
  metro_code number(8) not null default 0 comment '0 - country code valid only',
  region_code number(8) not null default 0,
  city_code number(8) not null default 0,
  postal_code varchar(12) not null default '',
  idft_isp number(8) not null default 0,
  idft_connection_speed number(3) not null default 0,
  idsite number(5) not null default 0,
  idevent_type number(5) not null default 0,
  guidn number(20) not null default 0,
  event_time timestamp_ntz not null default '1990-01-01 00:00:01'::timestamp_ntz,
  idplacement number(8) not null default 0,
  idcreative number(8) not null default 0,
  idcreative_config number(10) default null,
  ipn number(10) not null default 0,
  idft_domains number(10) not null default 0,
  idft_agents_cons number(8) not null default 0,
  idft_geo number(10) not null default 0,
  impression_id number(20) not null default 0,
  idviewableeventtype number(3) not null default 0,
  device_id varchar(128) default null comment 'external system id (eg idfa)',
  user_ids varchar(500) default null comment 'custom user ids eg. device 9',
  idagent_env number(1) not null default 0 comment 'impression was served: 1 = in app ; 0 = other ;',
  domain varchar(200) default null comment 'referrer url',
  ft_product varchar(250) default null comment 'product code - updated by state request',
  ft_data varchar(250) default null comment 'custom data - updated by state request',
  full_country_code number(5) not null default 0,
  browser_version varchar(15) default null,
  idbusiness_entity number(5) not null default 0,
  iab_flag char(1) not null default 'w',
  ft_tpplid varchar(50) default null,
  ft_c1 varchar(250) default null,
  ft_c2 varchar(250) default null,
  ft_c3 varchar(250) default null,
  agent_string varchar(250) default null,
  impression_guid varchar(40) default null,
  file_source varchar(),
  load_timestamp timestamp_ntz,
  run_datehour bigint
);

create table if not exists ft_db_{{ params.env }}.data_warehouse.interaction (
  idlog_file_control number(10) not null default 0,
  idinteraction_log number(10) not null default 0,
  event_date date not null default '1900-01-01'::date,
  idevent_type number(5) not null default 0,
  idcreative number(8) not null default 0,
  idplacement number(8) not null default 0,
  idcampaign number(9) not null default 0,
  idcreative_config number(10) default null,
  event_time timestamp_ntz not null default '1900-01-01 00:00:00'::timestamp_ntz,
  guidn number(20) not null default 0,
  sid number(20) default null,
  idad_index number(10) not null default 0,
  idsite number(5) not null default 0,
  idft_agents_os number(5) not null default 0,
  idft_agents_browsers number(8) not null default 0,
  idft_agents_devices number(8) not null default 0,
  device_type number(3) not null default 0 comment '1 = mobile; 2 = tablet; 3 = desktop; 0 = other;',
  country_code char(2) not null default '##',
  metro_code number(8) not null default 0 comment '0 - country code valid only',
  region_code number(8) not null default 0,
  city_code number(8) not null default 0,
  postal_code varchar(12) not null default '',
  idft_isp number(8) not null default 0,
  idft_connection_speed number(3) not null default 0,
  idbusiness_entity number(5) not null default 0,
  options varchar(255) default null,
  arrival_time timestamp_ntz,
  file_source varchar(),
  load_timestamp timestamp_ntz,
  run_datehour bigint
);

create table if not exists ft_db_{{ params.env }}.data_warehouse.onetag (
  idonetag_log number(9) not null default 0,
  idlog_file_control number(10) not null default 0,
  event_date date not null default '1900-00-00'::date,
  event_time timestamp_ntz not null default '1900-01-01 00:00:00'::timestamp_ntz,
  seg_data varchar(500) default null comment 'multiple segment data',
  referrer varchar(500) default null,
  ipn number(10) not null default 0 comment 'ip number',
  guidn number(20) not null default 0,
  idbusiness_entity number(5) not null default 0,
  idspotlight_group number(5) not null default 0,
  domain varchar(150) default null,
  path varchar(150) default null,
  user_query_string varchar(150) default null,
  file_source varchar(),
  load_timestamp timestamp_ntz,
  run_datehour bigint
);

create table if not exists ft_db_{{ params.env }}.data_warehouse.spot (
  idlog_file_control number(10) not null default 0,
  idspotlight_log number(9) not null default 0,
  event_date date not null default '1990-01-01'::date,
  idbusiness_entity number(5) not null default 0,
  idspotlight number(8) not null default 0,
  guidn number(20) not null default 0 comment 'guid number',
  guidn_created number(3) not null default 0 comment 'user had no guidn prior to firing this spotlight ; 0 = no ; 1 = yes ;',
  country_code char(2) default null,
  metro_code number(8) default null,
  region_code number(8) not null default 0,
  city_code number(8) default 0,
  postal_code varchar(12) not null default '',
  idft_connection_speed number(3) not null default 0,
  idspotlight_group number(5) not null default 0,
  original_spot_group number(5) not null default 0,
  qval number(15,2) not null default 0.00,
  qref varchar(150) default null comment 'ft xref if present',
  iab_flag char(1) not null default 'w',
  ipn number(10) not null default 0 comment 'ip number',
  idft_agents_cons number(8) not null default 0,
  idft_geo number(10) not null default 0,
  privacy_flag char(1) not null default 'x',
  idft_isp number(8) not null default 0,
  idft_agents_os number(5) not null default 0,
  idft_agents_browsers number(8) not null default 0,
  idft_agents_devices number(8) not null default 0,
  device_type number(3) not null default 0 comment '1 = mobile ; 2 = tablet ; 3 = desktop ; 0 = other ;',
  event_time timestamp_ntz not null default '1990-01-01 00:00:01'::timestamp_ntz comment 'gmt offset according to campaign',
  device_id varchar(128) default null comment 'external system id (eg idfa)',
  user_ids varchar(500) default null comment 'custom user ids eg. device 9',
  idagent_env number(1) not null default 0 comment 'impression was served: 1 = in app ; 0 = other ;',
  spotlight_request_id number(20) not null default 0 comment 'spotlight d9 state id',
  agent_string varchar(250) default null,
  spotlight_request_guid varchar(40) default null,
  query_string varchar(),
  file_source varchar(),
  load_timestamp timestamp_ntz,
  run_datehour bigint
);

create table if not exists ft_db_{{ params.env }}.data_warehouse.spots_matched (
  idspotlight_log number(8) default 0,
  idspotlight_log_file_control number(10) default 0,
  idmatched_log number(8) default 0,
  idmatched_log_file_control number(10) default 0,
  guidn number(20),
  user_id varchar(64) default '',
  iduser_id_type number(5) default 1,
  spot_date date,
  spot_time timestamp_ntz default '1990-01-01 00:00:01'::timestamp_ntz,
  matched_time timestamp_ntz default '1990-01-01 00:00:01'::timestamp_ntz,
  client_beid number(5) default 0,
  idcampaign number(9) default 0,
  idplacement number(8) default 0,
  idcreative number(8) default 0,
  idcreative_config number(10) default 0,
  idad_index number(10) default 0,
  idevent_type number(5) default 0,
  event_class char(1) default '',
  ft_section varchar(250) default null,
  ft_custom varchar(250) default null,
  idlog_keyword number(10) default 0,
  rule_flags number(3) default 0,
  idsite number(5) default 0,
  idspotlight_group number(5) default 0,
  channel_type number(3) default 0,
  idspotlight number(8) default 0,
  qref varchar(150) default null,
  impression_id number(20) default 0,
  spot_value number(15,2) default 0.00,
  log_keywords varchar(500) default null,
  ft_product varchar(250) default null comment 'product code from feed on click/imp',
  ft_data varchar(250) default null comment 'custom data from feed on click/imp',
  impression_guid varchar(40) default null,
  spotlight_request_guid varchar(40) default null,
  ft_tpplid varchar(50) default null,
  ft_c1 varchar(250) default null,
  ft_c2 varchar(250) default null,
  ft_c3 varchar(250) default null,
  device_type number(3) default 0 comment '1 = mobile ; 2 = tablet ; 3 = desktop ; 0 = other ;',
  idagent_env number(1) default 0 comment 'impression was served: 1 = in app ; 0 = other ;',
  placement_tree number(8) default 0,
  placement_tree_type char(1) default '' comment 'determine the type of tree used eg std, hedge',
  placement_path varchar(300) default null,
  creative_tree number(8) default 0,
  creative_tree_type char(1) default '' comment 'determine the type of tree used eg std, hedge',
  creative_path varchar(300) default null
);

create table if not exists ft_db_{{ params.env }}.data_warehouse.state (
  idlog_file_control number(10) not null default 0,
  idstate_log number(9) not null default 0,
  event_date date not null default '1990-01-01'::date,
  event_time timestamp_ntz not null default '1990-01-01 00:00:00'::timestamp_ntz,
  idevent_type number(5) not null default 0,
  idplacement number(8) not null default 0,
  impression_id number(20) not null default 0,
  idcreative number(8) not null default 0,
  idcreative_config number(10) not null default 0,
  ft_product varchar(250) default null,
  ft_data varchar(250) default null,
  idbusiness_entity number(5) not null default 0,
  impression_guid varchar(40) default null,
  file_source varchar(),
  load_timestamp timestamp_ntz,
  run_datehour bigint
);

create table if not exists ft_db_{{ params.env }}.data_warehouse.track (
  idlog_file_control number(10) not null default 0,
  idtrack_log number(9) not null default 0,
  event_date date not null default '1900-01-01'::date,
  event_time timestamp_ntz not null default '1900-01-01 00:00:00'::timestamp_ntz,
  idevent_type number(11) not null default 0,
  idspotlight number(8) not null default 0,
  idspotlight_group number(8) not null default 0,
  spotlight_request_id number(20) not null default 0,
  ft_product varchar(250) default null,
  ft_data varchar(250) default null,
  idbusiness_entity number(5) not null default 0,
  spotlight_request_guid varchar(40) default null,
  file_source varchar(),
  load_timestamp timestamp_ntz,
  run_datehour bigint
);
