schedule_interval: "35 * * * *"
tables:
     click:
       - ipn_blacklist
       - smart_clip_patch
     imp:
       - ipn_blacklist
       - smart_clip_patch
     int:
       - set_interaction_smartclip_placement
     state:
       - ipn_blacklist
stage_sql_path: adlogs/log_process
